In [1]:
from get_isochrone import generate_isochrone_grid, get_photometry_of_stars, wfc3_filters
from star_cluster import StarCluster
%pylab
messa_m51_filters = 'WFC3_UVIS_F336W', 'WFC3_UVIS_F275W', 'ACS_F435W', 'ACS_F555W', 'ACS_F814W'
chandar_filters = [
    "WFC3_UVIS_F336W",
    "WFC3_UVIS_F438W",
    "WFC3_UVIS_F555W",
    "WFC3_UVIS_F814W",
    "WFC3_UVIS_F657N",
]
#agegrid = np.logspace(5,10,101)
#grids = generate_isochrone_grid(agegrid, filters=chandar_filters)
from slugpy.cluster_slug import cluster_slug
import numpy as np
cs = cluster_slug(use_nebular=False,photsystem="Vega")
cs.add_filters(messa_m51_filters)

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [12]:
from filterlists import messa_m51_filters
sc = StarCluster(10**4)
agrid = np.logspace(5,10,31)

mass_measurements = [sc.measure(A,  measurement="MASS",cs=cs) for A in agrid]
#age_measurements = [sc.measure(A,  measurement="AGE",cs=cs) for A in agrid]

#sc.masses = np.array([2.,3.])
#phot = [sc.get_photometry(A,filters=messa_m51_filters,return_sum=True) for A in np.logspace(5,10,1000)]
#phot
#logm, pdf = cs.mpdf(0, phot)
#plt.plot(np.linspace(5,10,1000),phot)
#plt.plot(np.log10(np.sort(sc.masses)), phot[sc.masses.argsort()])

In [13]:
mass_measurements = np.array(mass_measurements)
plt.fill_between(np.log10(agrid), mass_measurements[:,0]-np.log10(sc.masses.sum()),mass_measurements[:,2]-np.log10(sc.masses.sum()))
plt.plot(np.log10(agrid),mass_measurements[:,1]-np.log10(sc.masses.sum()),color='black')
#age_measurements = np.array(age_measurements)
#plt.fill_between(np.log10(agrid),age_measurements[:,0],age_measurements[:,2])

In [2]:
def priorfunc(physprop):
    # Note: physprop is an array of shape (N, 3) where physprop[:,0] =
    # log M, physprop[:,1] = log T, physprop[:,2] = A_V
    return 1.0/np.exp(physprop[:,0])

mbests = []
tbests = []sc.get_photometry(1e6,filters=chandar_filters)
for i in range(10):
    sc = StarCluster(10**4)
    m = sc.get_stellar_masses()
    #len(m)
    L = get_photometry_of_stars(m, np.repeat(1e6,len(m)) * np.exp(np.random.normal(size=(len(m),))), agegrid, grids, magnitudes=True)
    print(L[L<100])
    L2= sc.get_photometry(1e6,filters=chandar_filters)
    print(L2[L2<100])
#     m_live = m[(np.min(L,axis=1)<100) + (m<1)]

#     phot = -2.5 * np.log10(np.sum(10**(-L/2.5),axis=0))

#     cs.priors = priorfunc
#     logM, logT, logA = cs.bestmatch(phot)[0][:3]
#     print(logM,logT,logA)
#     logm, pdf = cs.mpdf(0, phot)
#     logage, pdf_age = cs.mpdf(1, phot) #,qmin=5,qmax=10)#,qmin=-10,qmax=10,ngrid=1024) 
#     logA, pdf_A = cs.mpdf(2, phot)
#     plt.plot(10**logm/m_live.sum(),pdf); plt.xscale('log')
#     mbests.append(logm[pdf.argmax()])
#     tbests.append(logage[pdf_age.argmax()])
# np.std(mbests)
#tbests

/home/mgrudic/code/cluster_profile_sim/get_isochrone.py:135: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  mgrid1 = isochrone_grid[age_idx1, :, 0]


[1.18061339 1.44333688 1.47183735 ... 5.99069925 5.04935128 5.29012249]
[1.18061339 1.44333688 1.47183735 ... 5.99069925 5.04935128 5.29012249]
[1.64506797 1.75244946 1.74085694 ... 6.17378905 5.20203149 5.44987513]
[1.64506797 1.75244946 1.74085694 ... 6.17378905 5.20203149 5.44987513]
[2.36805967 2.41649843 2.29391209 ... 5.50629952 4.65241355 4.87287427]
[2.36805967 2.41649843 2.29391209 ... 5.50629952 4.65241355 4.87287427]
[2.3163115  2.35847967 2.24832449 ... 1.26103234 1.34852137 1.29074059]
[2.31910728 2.35861066 2.24827898 ... 1.26102282 1.34850234 1.29073108]
[ 2.5023215   2.57371473  2.41758107 ... -1.34112059 -1.06635987
 -1.25708397]
[ 2.5023215   2.57371473  2.41758107 ... -1.31539893 -1.03869571
 -1.23061752]
[6.85650203 6.65216016 5.8850276  ... 3.08236126 2.68901798 2.79226206]
[6.85650203 6.65216016 5.8850276  ... 3.08259461 2.68868702 2.79233458]
[6.98824041 6.74808209 5.96268333 ... 5.32985296 4.51029102 4.72216148]
[6.98824041 6.74808209 5.96268333 ... 5.32985296 4

In [19]:
#logA, pdf_A = cs.mpdf(2, phot)
#logA
plt.plot(logage,pdf_age)
#10**np.array(tbests)
#logage.max()
#logage[pdf_age.argmax()]


In [28]:
sc = StarCluster(10**4)
m = sc.get_stellar_masses()
#len(m)
L = get_photometry_of_stars(m, np.repeat(1e6,len(m)), agegrid, grids, magnitudes=True)
m_live = m[(np.min(L,axis=1)<100) + (m<1)]
m_live.max()
print(m_live.sum()/m.sum())
mmax = 100
imf_samples = np.load("kroupa_m300_samples.npy")
imf_samples = imf_samples[imf_samples < mmax]
np.sum(imf_samples[imf_samples < 8])/imf_samples.sum()
#plt.plot(np.log10(m[m.argsort()]),L[m.argsort()])

1.0


0.7878974

In [5]:
ogage, pdf_age = cs.mpdf(1, phot) #print(cs.__photsystem)


# Set priors to be flat in log T and A_V, but vary with log M as
# p(log M) ~ 1/M
def priorfunc(physprop):
   # Note: physprop is an array of shape (N, 3) where physprop[:,0] =
   # log M, physprop[:,1] = log T, physprop[:,2] = A_V
   return 1.0/np.exp(physprop[:,0])

cs.priors = priorfunc
logM, logT, logA = cs.bestmatch(phot)[0][:3]

logm, pdf = cs.mpdf(0, phot)
logage, pdf_age = cs.mpdf(1, phot,qmin=-10,qmax=10,ngrid=1024) 
logA, pdf_A = cs.mpdf(2, phot) 
plt.plot(logm,pdf)
#plt.plot(logage,pdf_age)
 # , photerr = photerr)
#logt, pdf = cs.pdf(0, phot)

/home/mgrudic/.local/lib/python3.9/site-packages/slugpy/bayesphot/bp.py:1800: RuntimeWarning: divide by zero encountered in divide
  pdf = np.transpose(np.transpose(pdf)/normfac)


In [6]:
ogage
#cs.bestmatch(phot)
#logT
#logM, logT*1e9
#cs.mcmc(phot)
#plt.plot(logm,pdf)
#np.diff(np.interp([0.16,0.84],pdf.cumsum()/pdf.sum(),logm))[0]/2
#10**logm[pdf.argmax()]/(m.sum())
#cs.mpdf
#logm,pdf
#phot
#pdf
#cs.bestmatch(phot[:4])

array([1.24447209e-06, 2.36232805e-02, 4.72453166e-02, 7.08673527e-02,
       9.44893888e-02, 1.18111425e-01, 1.41733461e-01, 1.65355497e-01,
       1.88977533e-01, 2.12599569e-01, 2.36221605e-01, 2.59843641e-01,
       2.83465677e-01, 3.07087713e-01, 3.30709749e-01, 3.54331786e-01,
       3.77953822e-01, 4.01575858e-01, 4.25197894e-01, 4.48819930e-01,
       4.72441966e-01, 4.96064002e-01, 5.19686038e-01, 5.43308074e-01,
       5.66930110e-01, 5.90552146e-01, 6.14174182e-01, 6.37796218e-01,
       6.61418254e-01, 6.85040291e-01, 7.08662327e-01, 7.32284363e-01,
       7.55906399e-01, 7.79528435e-01, 8.03150471e-01, 8.26772507e-01,
       8.50394543e-01, 8.74016579e-01, 8.97638615e-01, 9.21260651e-01,
       9.44882687e-01, 9.68504723e-01, 9.92126759e-01, 1.01574880e+00,
       1.03937083e+00, 1.06299287e+00, 1.08661490e+00, 1.11023694e+00,
       1.13385898e+00, 1.15748101e+00, 1.18110305e+00, 1.20472508e+00,
       1.22834712e+00, 1.25196916e+00, 1.27559119e+00, 1.29921323e+00,
      

In [15]:
p

False

In [16]:
agegrid = np.logspace(1,3,100)
num_ages = len(agegrid)
age = 273
logage_min, logage_max = np.log10(agegrid[0]), np.log10(agegrid[-1])
dlogage = np.log10(agegrid[1] / agegrid[0])
logage = np.log10(age)
#if logage < logage_min or logage > logage_max:
    #return np.nan
age_idx1 = int((logage - logage_min) / dlogage)
age_idx2 = age_idx1 + 1
agegrid[age_idx1], agegrid[age_idx2]
#logage1, logage2 = np.log10(agegrid[age_idx1]), np.log10(agegrid[age_idx2])
#wt_age1 = (logage - logage1) / dlogage

(271.85882427329403, 284.8035868435802)

In [8]:
np.diff(np.log10([get_photometry_of_stars(1., a, ages, grids) for a in ages]),axis=1)

6.0 6.0 10.113943352306837
1.0 0.0
6.004113943352307 6.0 10.113943352306837
1.0 0.0
6.0082278867046135 6.0 10.113943352306837
1.0 0.0
6.01234183005692 6.0 10.113943352306837
1.0 0.0
6.016455773409227 6.0 10.113943352306837
1.0 0.0
6.020569716761534 6.0 10.113943352306837
1.0 0.0
6.024683660113841 6.0 10.113943352306837
1.0 0.0
6.028797603466148 6.0 10.113943352306837
1.0 0.0
6.032911546818455 6.0 10.113943352306837
1.0 0.0
6.037025490170762 6.0 10.113943352306837
1.0 0.0
6.041139433523068 6.0 10.113943352306837
1.0 0.0
6.045253376875375 6.0 10.113943352306837
1.0 0.0
6.049367320227682 6.0 10.113943352306837
1.0 0.0
6.053481263579989 6.0 10.113943352306837
1.0 0.0
6.057595206932295 6.0 10.113943352306837
1.0 0.0
6.061709150284602 6.0 10.113943352306837
1.0 0.0
6.06582309363691 6.0 10.113943352306837
1.0 0.0
6.0699370369892165 6.0 10.113943352306837
1.0 0.0
6.074050980341523 6.0 10.113943352306837
1.0 0.0
6.07816492369383 6.0 10.113943352306837
1.0 0.0
6.082278867046137 6.0 10.1139433523

/tmp/ipykernel_933197/3924723745.py:1: RuntimeWarning: invalid value encountered in log10
  np.diff(np.log10([get_photometry_of_stars(1., a, ages, grids) for a in ages]),axis=1)


array([[0.09685381],
       [0.09685381],
       [0.09685381],
       ...,
       [       nan],
       [       nan],
       [       nan]])

In [8]:
 logage_min, logage_max = np.log10(agegrid[0]), np.log10(agegrid[1])
    dlogage = np.log10(agegrid[1] / agegrid[0])
    logage = np.log10(age)
    if logage < logage_min or logage > logage_max:
        return np.nan
    age_idx1 = int((num_ages - 1) * (logage - logage_min) / (logage_max - logage_min))
    age_idx2 = age_idx1 + 1
    logage1, logage2 = np.log10(agegrid[age_idx1]), np.log10(agegrid[age_idx2])
    wt_age1 = (logage - logage1) / dlogage

IndentationError: unexpected indent (2617093514.py, line 2)

In [2]:
len("------------------------------------------------------------------------------------------------------------------------------------------------------")

150

In [4]:
np.asarray(1.).shape[0]

IndexError: tuple index out of range